// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <Arduino.h>

#include "ui.h"
#include "ui_events.h"
#include "accessory.h"



//------------------------------------
void saveConfig(lv_event_t * e)
{
	save_config();
}

static int prev_left = 0;
static int prev_right = 0;

void setBrightness(lv_event_t *e) {
  lv_obj_t *slider = lv_event_get_target(e); // Get the slider that triggered the event
  int left = lv_slider_get_left_value(slider);
  int right = lv_slider_get_value(slider);

  if (left != prev_left) {
    // Left handle is being moved
    dim_brightness = left;
    tft.setBrightness(dim_brightness);
    prev_left = left;
    dim = true;
  }
  if (right != prev_right) {
    // Right handle is being moved
    brightness = right;
    tft.setBrightness(brightness);
    prev_right = right;
    dim = false;
  }
}

void setVolume(lv_event_t *e) {
  lv_obj_t *slider = lv_event_get_target(e); // Get the slider that triggered the event
  int slider_value = lv_slider_get_value(slider); // Extract the slider value (e.g., 0–255)
  volume = slider_value;
  clickSound();
}


void turnsoundon(lv_event_t * e)
{
	clickSound();
	sound_on = true;
}

void turnsoundoff(lv_event_t * e)
{
	clickSound();
	sound_on = false;
}

void rotateScreen(lv_event_t * e)
{
	clickSound();
  flip = true;
  rotation = rotation + 2;
  tft.setRotation(rotation);
  lv_obj_invalidate(lv_scr_act());
}

void notRotateScreen(lv_event_t * e)
{
	flip = false;
  rotation = rotation - 2;
  tft.setRotation(rotation);
  lv_obj_invalidate(lv_scr_act());
}