// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setBrightness(lv_event_t * e);
void setVolume(lv_event_t * e);
void turnsoundon(lv_event_t * e);
void turnsoundoff(lv_event_t * e);
void rotateScreen(lv_event_t * e);
void notRotateScreen(lv_event_t * e);
void saveConfig(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
