// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_SETTING_H
#define UI_SCREEN_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_setting
extern void ui_Screen_setting_screen_init(void);
extern void ui_Screen_setting_screen_destroy(void);
extern void ui_event_Screen_setting( lv_event_t * e);
extern lv_obj_t *ui_Screen_setting;
extern lv_obj_t *ui_setting_Textarea_message;
extern lv_obj_t *ui_setting_Label_Label1;
extern void ui_event_setting_Slider_backlight( lv_event_t * e);
extern lv_obj_t *ui_setting_Slider_backlight;
extern void ui_event_setting_Slider_volume( lv_event_t * e);
extern lv_obj_t *ui_setting_Slider_volume;
extern void ui_event_setting_Switch_sound( lv_event_t * e);
extern lv_obj_t *ui_setting_Switch_sound;
extern void ui_event_setting_Button_saveconfig( lv_event_t * e);
extern lv_obj_t *ui_setting_Button_saveconfig;
extern lv_obj_t *ui_setting_Label_Label2;
extern lv_obj_t *ui_setting_Label_version;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

