// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen_title1 = NULL;
// event funtions
void ui_event_Screen_title1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Screen_main, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 3000, &ui_Screen_main_screen_init);
}
}

// build funtions

void ui_Screen_title1_screen_init(void)
{
ui_Screen_title1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_title1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen_title1, &ui_img_taptappaw_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_Screen_title1, ui_event_Screen_title1, LV_EVENT_ALL, NULL);

}

void ui_Screen_title1_screen_destroy(void)
{
   if (ui_Screen_title1) lv_obj_del(ui_Screen_title1);

// NULL screen variables
ui_Screen_title1= NULL;

}
